version: "3"
services:
  app:
    container_name: componentmanager-front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
# version: "3"
# services:
#   frontend:
#     container_name: front-proj-ham-gian
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#   nginx:
#     image: nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     depends_on:
#       - frontend
